id: P000004
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 2021-12-16 15:04:36.105132
source_metadata:
  id: bdr:W2KG210298
  title: བཀའ་འགྱུར། ༼ཧེ་མིས་བྲིས་མ།༽
  author: ''
  volumes:
    da80e2876ad746ab985ca6affd187148:
      image_group_id: I2KG211011
      title: ''
      volume_number: 1
      total_pages: 321
    f7525909dd2745798fc8f56ecf3a2467:
      image_group_id: I2KG211012
      title: ''
      volume_number: 2
      total_pages: 331
    b5bb38f8ac4d4cf09b111565ab8f3038:
      image_group_id: I2KG211013
      title: ''
      volume_number: 3
      total_pages: 323
    b08071251289427d824930444947f347:
      image_group_id: I2KG211014
      title: ''
      volume_number: 4
      total_pages: 496
    5749a3e621b243ceb14080d6accea7a8:
      image_group_id: I2KG211015
      title: ''
      volume_number: 5
      total_pages: 870
    d784d1d94e874455b651fc43833c68b0:
      image_group_id: I2KG211016
      title: ''
      volume_number: 6
      total_pages: 776
    4d94fb6a83464b428efe15e821a91692:
      image_group_id: I2KG211017
      title: ''
      volume_number: 7
      total_pages: 971
    9494705563694640b65527eb8aa8d4d2:
      image_group_id: I2KG211018
      title: ''
      volume_number: 8
      total_pages: 470
    64406b4f9c484d3ab7b595ca2f7aa616:
      image_group_id: I2KG211019
      title: ''
      volume_number: 9
      total_pages: 356
    5ecb1418f35f4f99897a7046324eac20:
      image_group_id: I2KG211020
      title: ''
      volume_number: 10
      total_pages: 0
    74783879e6774239a6d2e47a776a53b5:
      image_group_id: I2KG211021
      title: ''
      volume_number: 11
      total_pages: 280
    b079bec4e9b049319451093ddba47d17:
      image_group_id: I2KG211022
      title: ''
      volume_number: 12
      total_pages: 155
    24887100b92e4d22994b510848807065:
      image_group_id: I2KG211023
      title: ''
      volume_number: 13
      total_pages: 434
    02480483a8884bd5bac6c7fb7714133d:
      image_group_id: I2KG211024
      title: ''
      volume_number: 14
      total_pages: 586
    148b52f3ba6d4f11b0b82118d9a482a3:
      image_group_id: I2KG211025
      title: ''
      volume_number: 15
      total_pages: 0
    be4ca8603f8748b5b739f032cb0c39a3:
      image_group_id: I2KG211026
      title: ''
      volume_number: 16
      total_pages: 0
    61562e82715247deae710cbba1076c00:
      image_group_id: I2KG211027
      title: ''
      volume_number: 17
      total_pages: 434
    c2efe24a201a450abdbcc3e6cb7fecfc:
      image_group_id: I2KG211028
      title: ''
      volume_number: 18
      total_pages: 544
    7de9654311ac437ea1d0bfd483518b9a:
      image_group_id: I2KG211029
      title: ''
      volume_number: 19
      total_pages: 473
    411db4c1df2d4c5cb4dae6864b6aaee7:
      image_group_id: I2KG211030
      title: ''
      volume_number: 20
      total_pages: 472
    5a28dee43a2a45d6a39c3d4a2fc42271:
      image_group_id: I2KG211031
      title: ''
      volume_number: 21
      total_pages: 451
    b080d6de96b34aee8a9f0d4e73303fd5:
      image_group_id: I2KG211032
      title: ''
      volume_number: 22
      total_pages: 454
    ecbc2082a925481b98e38730d34b8ef2:
      image_group_id: I2KG211033
      title: ''
      volume_number: 23
      total_pages: 276
    593c8b5efca0413f9e3977c9613b83fe:
      image_group_id: I2KG211034
      title: ''
      volume_number: 24
      total_pages: 0
    af6b1d245b084bea997a4f5d53af6b07:
      image_group_id: I2KG211035
      title: ''
      volume_number: 25
      total_pages: 741
    0fc71b7e328d4960a89d3800de9d1458:
      image_group_id: I2KG211036
      title: ''
      volume_number: 26
      total_pages: 396
    dc110d7fbbc74ea388596093aa3b654b:
      image_group_id: I2KG211037
      title: ''
      volume_number: 27
      total_pages: 0
    c49144df507442a89ab675a6673216b1:
      image_group_id: I2KG211038
      title: ''
      volume_number: 28
      total_pages: 305
    ef519fa67012464bae43c3a425d232d5:
      image_group_id: I2KG211039
      title: ''
      volume_number: 29
      total_pages: 373
    f299970a69924760bac3e4022c81d6b4:
      image_group_id: I2KG211040
      title: ''
      volume_number: 30
      total_pages: 573
    4e6e5464e41f4f9d8d94ed247cd8b956:
      image_group_id: I2KG211041
      title: ''
      volume_number: 31
      total_pages: 372
    5be895d9e1604838aacb197d21d1b98e:
      image_group_id: I2KG211042
      title: ''
      volume_number: 32
      total_pages: 351
    a0dcfe8cf96541f48aa25edc10ca5cf7:
      image_group_id: I2KG211043
      title: ''
      volume_number: 33
      total_pages: 560
    da79c95fcf8f4c32b4f1e257f65b0a3c:
      image_group_id: I2KG211044
      title: ''
      volume_number: 34
      total_pages: 767
    4c8f8790bca84731a34222a1b6cdb0b8:
      image_group_id: I2KG211045
      title: ''
      volume_number: 35
      total_pages: 595
    2a32cf53be6d4b878fcf35b24606c14d:
      image_group_id: I2KG211046
      title: ''
      volume_number: 36
      total_pages: 798
    f4df0d2cfd8e48a6bd7225fd24615ac9:
      image_group_id: I2KG211047
      title: ''
      volume_number: 37
      total_pages: 619
    659b90ef546d4b63bc8fbb98c2f9aaad:
      image_group_id: I2KG211048
      title: ''
      volume_number: 38
      total_pages: 794
    964d33426994418ebf43fd510af5d53d:
      image_group_id: I2KG211049
      title: ''
      volume_number: 39
      total_pages: 577
    7baffd98d15e4e08bb4cfd7e238f5829:
      image_group_id: I2KG211050
      title: ''
      volume_number: 40
      total_pages: 914
    3c99394b75d44ce4808fa00cf92c1b47:
      image_group_id: I2KG211051
      title: ''
      volume_number: 41
      total_pages: 580
    d5cfcbf18d3a4e27b19da5d711beec83:
      image_group_id: I2KG211052
      title: ''
      volume_number: 42
      total_pages: 467
    2b3dc501603e4103b85ebdc107a8d930:
      image_group_id: I2KG211053
      title: ''
      volume_number: 43
      total_pages: 466
    53e96b60e8ec47d89909c1958130d29e:
      image_group_id: I2KG211054
      title: ''
      volume_number: 44
      total_pages: 0
    0a4550840ccb4fb59b6a8412523314b5:
      image_group_id: I2KG211055
      title: ''
      volume_number: 45
      total_pages: 0
    583629137a9b4c07ab07974b20b9a359:
      image_group_id: I2KG211056
      title: ''
      volume_number: 46
      total_pages: 244
    8686f7f94fbc488d9205e1402d6da009:
      image_group_id: I2KG211057
      title: ''
      volume_number: 47
      total_pages: 288
    779ece45c21c4f94bdb1793f839339ad:
      image_group_id: I2KG211058
      title: ''
      volume_number: 48
      total_pages: 188
    264bc56273bd4a80824dee7bd17421f6:
      image_group_id: I2KG211059
      title: ''
      volume_number: 49
      total_pages: 360
    0f64a4bd60b446ee90cde5771a58c6a4:
      image_group_id: I2KG211060
      title: ''
      volume_number: 50
      total_pages: 250
    64682945da0c47249ade6bb4ffa36a03:
      image_group_id: I2KG211061
      title: ''
      volume_number: 51
      total_pages: 122
    4c08b7b428e34a59a2ba8ca3c2b3095c:
      image_group_id: I2KG211062
      title: ''
      volume_number: 52
      total_pages: 0
    d5f35e7b71bb46f18d62dff17091bb48:
      image_group_id: I2KG211063
      title: ''
      volume_number: 53
      total_pages: 196
    654d2431e8474965989e56285bdd588f:
      image_group_id: I2KG211064
      title: ''
      volume_number: 54
      total_pages: 291
    ae50598625ff49458f020b84bad2fcc8:
      image_group_id: I2KG211065
      title: ''
      volume_number: 55
      total_pages: 0
    c3adb3e4e1724e84ac7e2c0d5d0e2da1:
      image_group_id: I2KG211066
      title: ''
      volume_number: 56
      total_pages: 315
    35fb3cdecd8d421bac49f45b47d582a9:
      image_group_id: I2KG211067
      title: ''
      volume_number: 57
      total_pages: 197
    61dd4dbdd4d6433e94431cb69ed7d922:
      image_group_id: I2KG211068
      title: ''
      volume_number: 58
      total_pages: 317
    2b40e0eeda6b4d3dac748b3ec9b5fd47:
      image_group_id: I2KG211069
      title: ''
      volume_number: 59
      total_pages: 346
    bee191ae5ef1477d80230daf5c737888:
      image_group_id: I2KG211070
      title: ''
      volume_number: 60
      total_pages: 440
    8d6771ce83c74069ae055a9b0a2e1102:
      image_group_id: I2KG211071
      title: ''
      volume_number: 61
      total_pages: 66
    b73dc7bd0fd0483f9c911c88c28fc3c5:
      image_group_id: I2KG211072
      title: ''
      volume_number: 62
      total_pages: 100
    bf9fe425f22b4b06afa52a175590f17e:
      image_group_id: I2KG211073
      title: ''
      volume_number: 63
      total_pages: 75
    ae7b4b00af334567a675fe10739203ba:
      image_group_id: I2KG211074
      title: ''
      volume_number: 64
      total_pages: 265
    c50cda56b8584ad3a198210d6f419249:
      image_group_id: I2KG211075
      title: ''
      volume_number: 65
      total_pages: 424
    b6ec1807e9af42429bea4d6939713b5b:
      image_group_id: I2KG211076
      title: ''
      volume_number: 66
      total_pages: 285
    efeef484318a4c249e03bfce46f974bf:
      image_group_id: I2KG211077
      title: ''
      volume_number: 67
      total_pages: 512
    ea740639ca5141f686c13cd8c274eb9e:
      image_group_id: I2KG211078
      title: ''
      volume_number: 68
      total_pages: 328
    423973e26d654d0f994dd7052f99649b:
      image_group_id: I2KG211079
      title: ''
      volume_number: 69
      total_pages: 634
    a0c2f050153d49afa4666629c1c099aa:
      image_group_id: I2KG211080
      title: ''
      volume_number: 70
      total_pages: 191
    d3ee0f83c52349c994475c6cee8ec39c:
      image_group_id: I2KG211081
      title: ''
      volume_number: 71
      total_pages: 338
    b229ae098b9f4278b5c527daa2836138:
      image_group_id: I2KG211082
      title: ''
      volume_number: 72
      total_pages: 544
    6b4ca12e39b249e5b483b0f71c100a81:
      image_group_id: I2KG211083
      title: ''
      volume_number: 73
      total_pages: 199
    a18c76d2e986400481cae4183512bf3e:
      image_group_id: I2KG211084
      title: ''
      volume_number: 74
      total_pages: 616
    96ea6167ff874119b5c757676564e40d:
      image_group_id: I2KG211085
      title: ''
      volume_number: 75
      total_pages: 642
    18d3fb49907141ec9ffb40583ca765da:
      image_group_id: I2KG211086
      title: ''
      volume_number: 76
      total_pages: 238
    98be903e857d408d86b7619cf63d48be:
      image_group_id: I2KG211087
      title: ''
      volume_number: 77
      total_pages: 180
    5bd95f84c1d14038b705d7505f97d56f:
      image_group_id: I2KG211088
      title: ''
      volume_number: 78
      total_pages: 289
    dccd76eb94de4f6485fd867e1adc5caf:
      image_group_id: I2KG211089
      title: ''
      volume_number: 79
      total_pages: 368
    ed91f95362364da9845a1e1c3dc4ebea:
      image_group_id: I2KG211090
      title: ''
      volume_number: 80
      total_pages: 289
    9f98b64882dc43b4a638977dc78cc5e6:
      image_group_id: I2KG211091
      title: ''
      volume_number: 81
      total_pages: 250
    3ca7817ec4e54959ad8a1edf9fcad27d:
      image_group_id: I2KG211092
      title: ''
      volume_number: 82
      total_pages: 476
    20306585afe44b91a2bf32cd021f2530:
      image_group_id: I2KG211093
      title: ''
      volume_number: 83
      total_pages: 193
    4f6676e2c0c34087800679bd8d63b9dc:
      image_group_id: I2KG211094
      title: ''
      volume_number: 84
      total_pages: 241
    b9f4b411c3f1422d8c5059b60e3b5d5a:
      image_group_id: I2KG211095
      title: ''
      volume_number: 85
      total_pages: 40
    2ee9b8a508c04ef1808ab98a91101d17:
      image_group_id: I2KG211096
      title: ''
      volume_number: 86
      total_pages: 243
    e6b8915443ee4458aacec61eedb426d2:
      image_group_id: I2KG211097
      title: ''
      volume_number: 87
      total_pages: 164
    c5dadba579964a09869cb3cbb10f50a0:
      image_group_id: I2KG211098
      title: ''
      volume_number: 88
      total_pages: 303
    2d12a41417ba46e284f5ec9d69cc19bd:
      image_group_id: I2KG211099
      title: ''
      volume_number: 89
      total_pages: 352
    2cca39b1a8574b56b10f2f1ba5f4070e:
      image_group_id: I2KG211100
      title: ''
      volume_number: 90
      total_pages: 224
    0c42d199319a47bbb72dce9951ffb7ba:
      image_group_id: I2KG211101
      title: ''
      volume_number: 91
      total_pages: 264
    f9731b3a6271425c838af85a7956b020:
      image_group_id: I2KG211102
      title: ''
      volume_number: 92
      total_pages: 0
    20774ed9b0d04309a015bd808fadd90c:
      image_group_id: I2KG211103
      title: ''
      volume_number: 93
      total_pages: 0
    6b72f7866c0f4b64917d5acaae977b9b:
      image_group_id: I2KG211104
      title: ''
      volume_number: 94
      total_pages: 338
    fa526495de0049b7adc46dd81b5b398a:
      image_group_id: I2KG211105
      title: ''
      volume_number: 95
      total_pages: 0
    38fc6f11fac449ab8c912b265270cd31:
      image_group_id: I2KG211106
      title: ''
      volume_number: 96
      total_pages: 0
    ae6bfc0484a743a591d1701c81c2afe7:
      image_group_id: I2KG211107
      title: ''
      volume_number: 97
      total_pages: 0
    bd7718e1ee6a487ab8800cddfb5de648:
      image_group_id: I2KG211108
      title: ''
      volume_number: 98
      total_pages: 0
    bd96bb5b6cdf497ca905f3e287a80384:
      image_group_id: I2KG211109
      title: ''
      volume_number: 99
      total_pages: 456
    709670b57cf147a7a94410e695fc8249:
      image_group_id: I2KG211110
      title: ''
      volume_number: 100
      total_pages: 424
    7fbaaee6089a47b5be9898a198b247ef:
      image_group_id: I2KG211111
      title: ''
      volume_number: 101
      total_pages: 0
    496387d624db43448e7a3daa1e373600:
      image_group_id: I2KG211112
      title: ''
      volume_number: 102
      total_pages: 420
    7b18b0df22a145778d9f411fc9811d62:
      image_group_id: I2KG211113
      title: ''
      volume_number: 103
      total_pages: 0
    be6a3161a8b3421aa7d63590edab3e52:
      image_group_id: I2KG211114
      title: ''
      volume_number: 104
      total_pages: 122
    62d8c313b799442086391d3d7e8acac6:
      image_group_id: I2KG211115
      title: ''
      volume_number: 105
      total_pages: 321
    27fee4ec8eb4499b8d777cb72cc71466:
      image_group_id: I2KG211116
      title: ''
      volume_number: 106
      total_pages: 24
    95634c7ee37642aabbfff2a423e062f2:
      image_group_id: I2KG211117
      title: ''
      volume_number: 107
      total_pages: 168
    850820fc29b54c9298f5b65892e084f9:
      image_group_id: I2KG211118
      title: ''
      volume_number: 108
      total_pages: 975
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
