id: I55341BE1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T18:03:38+00:00'
last_modified: '2022-06-07T11:21:34.143302+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2KG210298
  title: བཀའ་འགྱུར། ༼ཧེ་མིས་བྲིས་མ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    447B:
      image_group_id: I2KG211011
      title: ''
      total_pages: 321
      order: 1
      base_file: 447B.txt
    9D19:
      image_group_id: I2KG211012
      title: ''
      total_pages: 331
      order: 2
      base_file: 9D19.txt
    CD39:
      image_group_id: I2KG211013
      title: ''
      total_pages: 323
      order: 3
      base_file: CD39.txt
    ED80:
      image_group_id: I2KG211014
      title: ''
      total_pages: 496
      order: 4
      base_file: ED80.txt
    CA54:
      image_group_id: I2KG211015
      title: ''
      total_pages: 870
      order: 5
      base_file: CA54.txt
    '0334':
      image_group_id: I2KG211016
      title: ''
      total_pages: 776
      order: 6
      base_file: 0334.txt
    D5B1:
      image_group_id: I2KG211017
      title: ''
      total_pages: 971
      order: 7
      base_file: D5B1.txt
    A060:
      image_group_id: I2KG211018
      title: ''
      total_pages: 470
      order: 8
      base_file: A060.txt
    EB9B:
      image_group_id: I2KG211019
      title: ''
      total_pages: 356
      order: 9
      base_file: EB9B.txt
    A709:
      image_group_id: I2KG211021
      title: ''
      total_pages: 280
      order: 11
      base_file: A709.txt
    E1B1:
      image_group_id: I2KG211022
      title: ''
      total_pages: 155
      order: 12
      base_file: E1B1.txt
    F1D2:
      image_group_id: I2KG211023
      title: ''
      total_pages: 434
      order: 13
      base_file: F1D2.txt
    CE34:
      image_group_id: I2KG211024
      title: ''
      total_pages: 586
      order: 14
      base_file: CE34.txt
    '8480':
      image_group_id: I2KG211027
      title: ''
      total_pages: 434
      order: 17
      base_file: 8480.txt
    EC0A:
      image_group_id: I2KG211028
      title: ''
      total_pages: 544
      order: 18
      base_file: EC0A.txt
    0E19:
      image_group_id: I2KG211029
      title: ''
      total_pages: 473
      order: 19
      base_file: 0E19.txt
    467F:
      image_group_id: I2KG211030
      title: ''
      total_pages: 472
      order: 20
      base_file: 467F.txt
    C344:
      image_group_id: I2KG211031
      title: ''
      total_pages: 451
      order: 21
      base_file: C344.txt
    '9730':
      image_group_id: I2KG211032
      title: ''
      total_pages: 454
      order: 22
      base_file: 9730.txt
    132F:
      image_group_id: I2KG211033
      title: ''
      total_pages: 276
      order: 23
      base_file: 132F.txt
    CEE9:
      image_group_id: I2KG211035
      title: ''
      total_pages: 741
      order: 25
      base_file: CEE9.txt
    871B:
      image_group_id: I2KG211036
      title: ''
      total_pages: 396
      order: 26
      base_file: 871B.txt
    942B:
      image_group_id: I2KG211038
      title: ''
      total_pages: 305
      order: 28
      base_file: 942B.txt
    79CF:
      image_group_id: I2KG211039
      title: ''
      total_pages: 373
      order: 29
      base_file: 79CF.txt
    D6AB:
      image_group_id: I2KG211040
      title: ''
      total_pages: 573
      order: 30
      base_file: D6AB.txt
    CC39:
      image_group_id: I2KG211041
      title: ''
      total_pages: 372
      order: 31
      base_file: CC39.txt
    DF41:
      image_group_id: I2KG211042
      title: ''
      total_pages: 351
      order: 32
      base_file: DF41.txt
    4B7A:
      image_group_id: I2KG211043
      title: ''
      total_pages: 560
      order: 33
      base_file: 4B7A.txt
    '0753':
      image_group_id: I2KG211044
      title: ''
      total_pages: 767
      order: 34
      base_file: 0753.txt
    B0DA:
      image_group_id: I2KG211045
      title: ''
      total_pages: 595
      order: 35
      base_file: B0DA.txt
    '2244':
      image_group_id: I2KG211046
      title: ''
      total_pages: 798
      order: 36
      base_file: 2244.txt
    AA6C:
      image_group_id: I2KG211047
      title: ''
      total_pages: 619
      order: 37
      base_file: AA6C.txt
    9C43:
      image_group_id: I2KG211048
      title: ''
      total_pages: 794
      order: 38
      base_file: 9C43.txt
    3CDA:
      image_group_id: I2KG211049
      title: ''
      total_pages: 577
      order: 39
      base_file: 3CDA.txt
    '4509':
      image_group_id: I2KG211050
      title: ''
      total_pages: 914
      order: 40
      base_file: 4509.txt
    '4890':
      image_group_id: I2KG211051
      title: ''
      total_pages: 580
      order: 41
      base_file: 4890.txt
    '3908':
      image_group_id: I2KG211052
      title: ''
      total_pages: 467
      order: 42
      base_file: 3908.txt
    0AB6:
      image_group_id: I2KG211053
      title: ''
      total_pages: 466
      order: 43
      base_file: 0AB6.txt
    '2599':
      image_group_id: I2KG211056
      title: ''
      total_pages: 244
      order: 46
      base_file: 2599.txt
    3E4E:
      image_group_id: I2KG211057
      title: ''
      total_pages: 288
      order: 47
      base_file: 3E4E.txt
    A505:
      image_group_id: I2KG211058
      title: ''
      total_pages: 188
      order: 48
      base_file: A505.txt
    B1A4:
      image_group_id: I2KG211059
      title: ''
      total_pages: 360
      order: 49
      base_file: B1A4.txt
    96CD:
      image_group_id: I2KG211060
      title: ''
      total_pages: 250
      order: 50
      base_file: 96CD.txt
    B60E:
      image_group_id: I2KG211061
      title: ''
      total_pages: 122
      order: 51
      base_file: B60E.txt
    CBEC:
      image_group_id: I2KG211063
      title: ''
      total_pages: 196
      order: 53
      base_file: CBEC.txt
    DA80:
      image_group_id: I2KG211064
      title: ''
      total_pages: 291
      order: 54
      base_file: DA80.txt
    B980:
      image_group_id: I2KG211066
      title: ''
      total_pages: 315
      order: 56
      base_file: B980.txt
    D8B8:
      image_group_id: I2KG211067
      title: ''
      total_pages: 197
      order: 57
      base_file: D8B8.txt
    D486:
      image_group_id: I2KG211068
      title: ''
      total_pages: 317
      order: 58
      base_file: D486.txt
    787A:
      image_group_id: I2KG211069
      title: ''
      total_pages: 346
      order: 59
      base_file: 787A.txt
    B0D7:
      image_group_id: I2KG211070
      title: ''
      total_pages: 440
      order: 60
      base_file: B0D7.txt
    2DD2:
      image_group_id: I2KG211071
      title: ''
      total_pages: 66
      order: 61
      base_file: 2DD2.txt
    533D:
      image_group_id: I2KG211072
      title: ''
      total_pages: 100
      order: 62
      base_file: 533D.txt
    788B:
      image_group_id: I2KG211073
      title: ''
      total_pages: 75
      order: 63
      base_file: 788B.txt
    77FA:
      image_group_id: I2KG211074
      title: ''
      total_pages: 265
      order: 64
      base_file: 77FA.txt
    9A35:
      image_group_id: I2KG211075
      title: ''
      total_pages: 424
      order: 65
      base_file: 9A35.txt
    C8D8:
      image_group_id: I2KG211076
      title: ''
      total_pages: 285
      order: 66
      base_file: C8D8.txt
    EEEF:
      image_group_id: I2KG211077
      title: ''
      total_pages: 512
      order: 67
      base_file: EEEF.txt
    E873:
      image_group_id: I2KG211078
      title: ''
      total_pages: 328
      order: 68
      base_file: E873.txt
    '9553':
      image_group_id: I2KG211079
      title: ''
      total_pages: 634
      order: 69
      base_file: 9553.txt
    CA8F:
      image_group_id: I2KG211080
      title: ''
      total_pages: 191
      order: 70
      base_file: CA8F.txt
    '8525':
      image_group_id: I2KG211081
      title: ''
      total_pages: 338
      order: 71
      base_file: 8525.txt
    3E2E:
      image_group_id: I2KG211082
      title: ''
      total_pages: 544
      order: 72
      base_file: 3E2E.txt
    F16C:
      image_group_id: I2KG211083
      title: ''
      total_pages: 199
      order: 73
      base_file: F16C.txt
    0A71:
      image_group_id: I2KG211084
      title: ''
      total_pages: 616
      order: 74
      base_file: 0A71.txt
    BAF0:
      image_group_id: I2KG211085
      title: ''
      total_pages: 642
      order: 75
      base_file: BAF0.txt
    D35A:
      image_group_id: I2KG211086
      title: ''
      total_pages: 238
      order: 76
      base_file: D35A.txt
    55B7:
      image_group_id: I2KG211087
      title: ''
      total_pages: 180
      order: 77
      base_file: 55B7.txt
    34A4:
      image_group_id: I2KG211088
      title: ''
      total_pages: 289
      order: 78
      base_file: 34A4.txt
    '8810':
      image_group_id: I2KG211089
      title: ''
      total_pages: 368
      order: 79
      base_file: 8810.txt
    03B9:
      image_group_id: I2KG211090
      title: ''
      total_pages: 289
      order: 80
      base_file: 03B9.txt
    09FC:
      image_group_id: I2KG211091
      title: ''
      total_pages: 250
      order: 81
      base_file: 09FC.txt
    E31A:
      image_group_id: I2KG211092
      title: ''
      total_pages: 476
      order: 82
      base_file: E31A.txt
    054C:
      image_group_id: I2KG211093
      title: ''
      total_pages: 193
      order: 83
      base_file: 054C.txt
    '4281':
      image_group_id: I2KG211094
      title: ''
      total_pages: 241
      order: 84
      base_file: 4281.txt
    A1F3:
      image_group_id: I2KG211095
      title: ''
      total_pages: 40
      order: 85
      base_file: A1F3.txt
    DAB7:
      image_group_id: I2KG211096
      title: ''
      total_pages: 243
      order: 86
      base_file: DAB7.txt
    461B:
      image_group_id: I2KG211097
      title: ''
      total_pages: 164
      order: 87
      base_file: 461B.txt
    B314:
      image_group_id: I2KG211098
      title: ''
      total_pages: 303
      order: 88
      base_file: B314.txt
    D949:
      image_group_id: I2KG211099
      title: ''
      total_pages: 352
      order: 89
      base_file: D949.txt
    84C8:
      image_group_id: I2KG211100
      title: ''
      total_pages: 224
      order: 90
      base_file: 84C8.txt
    '7270':
      image_group_id: I2KG211101
      title: ''
      total_pages: 264
      order: 91
      base_file: 7270.txt
    '9846':
      image_group_id: I2KG211104
      title: ''
      total_pages: 338
      order: 94
      base_file: 9846.txt
    0DCC:
      image_group_id: I2KG211109
      title: ''
      total_pages: 456
      order: 99
      base_file: 0DCC.txt
    22E9:
      image_group_id: I2KG211110
      title: ''
      total_pages: 424
      order: 100
      base_file: 22E9.txt
    '6791':
      image_group_id: I2KG211112
      title: ''
      total_pages: 420
      order: 102
      base_file: 6791.txt
    '4396':
      image_group_id: I2KG211114
      title: ''
      total_pages: 122
      order: 104
      base_file: 4396.txt
    '7338':
      image_group_id: I2KG211115
      title: ''
      total_pages: 321
      order: 105
      base_file: 7338.txt
    56D0:
      image_group_id: I2KG211116
      title: ''
      total_pages: 24
      order: 106
      base_file: 56D0.txt
    '5566':
      image_group_id: I2KG211117
      title: ''
      total_pages: 168
      order: 107
      base_file: 5566.txt
    1E49:
      image_group_id: I2KG211118
      title: ''
      total_pages: 975
      order: 108
      base_file: 1E49.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
